package de.yourshika.betterpets.quickslots.ui;

import net.minecraft.client.gui.GuiGraphicsExtractor;
import net.minecraft.client.renderer.RenderPipelines;
import net.minecraft.resources.Identifier;

/**
 * The textures the interface is built from. All of them are GUI sprites generated by
 * {@code tools/make_sprites.py}: the stretchable ones (panels, slots, buttons) are nine-sliced by the
 * game through their {@code .mcmeta}, so they can be drawn at any size without their borders smearing.
 */
public final class Sprites {

    private static final String NAMESPACE = "betterpets-quickslots";

    // --- stretchable ---
    public static final Identifier PANEL = id("panel");
    public static final Identifier INSET = id("inset");
    public static final Identifier SLOT = id("slot");
    public static final Identifier FRAME_GOLD = id("frame_gold");
    public static final Identifier CARD = id("card");
    public static final Identifier CARD_HOVER = id("card_hover");
    public static final Identifier BUTTON = id("button");
    public static final Identifier BUTTON_HOVER = id("button_hover");
    public static final Identifier BUTTON_DISABLED = id("button_disabled");
    public static final Identifier TAB = id("tab");
    public static final Identifier TAB_HOVER = id("tab_hover");
    public static final Identifier TAB_ACTIVE = id("tab_active");
    public static final Identifier SLIDER_TRACK = id("slider_track");
    public static final Identifier SLIDER_FILL = id("slider_fill");
    public static final Identifier KEY_CAP = id("key_cap");

    // --- fixed size (width x height in the comment) ---
    public static final Identifier TOGGLE_OFF = id("toggle_off");          // 30 x 14
    public static final Identifier TOGGLE_ON = id("toggle_on");            // 30 x 14
    public static final Identifier TOGGLE_KNOB = id("toggle_knob");        // 12 x 12
    public static final Identifier SLIDER_KNOB = id("slider_knob");        // 8 x 14
    public static final Identifier WHEEL_RING = id("wheel_ring");          // 200 x 200
    public static final Identifier WHEEL_RING_SMALL = id("wheel_ring_small"); // 88 x 88
    public static final Identifier WHEEL_HUB = id("wheel_hub");            // 72 x 72
    public static final Identifier WHEEL_NODE = id("wheel_node");          // 44 x 44
    public static final Identifier WHEEL_NODE_GOLD = id("wheel_node_gold"); // 48 x 48
    public static final Identifier WHEEL_POINTER = id("wheel_pointer");    // 15 x 12
    public static final Identifier GLOW = id("glow");                      // 64 x 64, white: tint it
    public static final Identifier SPARK = id("spark");                    // 9 x 9, white: tint it
    public static final Identifier GEM_GREEN = id("gem_green");            // 6 x 6
    public static final Identifier LOCK = id("lock");                      // 11 x 12
    public static final Identifier SCENE = id("scene");                    // 256 x 144

    // --- 16 x 16 icons from the Better Pets artwork ---
    public static final Identifier ICON_CLOSE = id("icon/close");
    public static final Identifier ICON_BACK = id("icon/back");
    public static final Identifier ICON_NEXT = id("icon/next");
    public static final Identifier ICON_PREVIOUS = id("icon/previous");
    public static final Identifier ICON_PUT_AWAY = id("icon/put_away");
    public static final Identifier ICON_EYE_ON = id("icon/eye_on");
    public static final Identifier ICON_EYE_OFF = id("icon/eye_off");
    public static final Identifier ICON_SEARCH = id("icon/search");
    public static final Identifier ICON_EMPTY = id("icon/empty");
    public static final Identifier ICON_STAR = id("icon/star");
    public static final Identifier ICON_LOCKED = id("icon/locked");
    public static final Identifier ICON_CHECK = id("icon/check");
    public static final Identifier ICON_CANCEL = id("icon/cancel");
    public static final Identifier ICON_MENU = id("icon/menu");
    public static final Identifier ICON_GEAR = id("icon/gear");
    public static final Identifier ICON_FOX = id("icon/fox");
    public static final Identifier ICON_CAT = id("icon/cat");
    public static final Identifier ICON_COIN = id("icon/coin");
    public static final Identifier ICON_SKIN = id("icon/skin");
    public static final Identifier ICON_RANK = id("icon/rank");
    public static final Identifier ICON_KEYS = id("icon/keys");
    public static final Identifier ICON_WHEEL = id("icon/wheel");

    // --- the characters that lean on the panels and stand by the wheel ---
    public static final Identifier CHARACTER_FOX = id("character/fox");       // 70 x 63
    public static final Identifier CHARACTER_OTTER = id("character/otter");   // 70 x 59
    public static final Identifier CHARACTER_CAT = id("character/cat");       // 70 x 60
    public static final Identifier CHARACTER_OWL = id("character/owl");       // 70 x 73
    public static final Identifier CHARACTER_MOON_FOX = id("character/moon_fox");       // 68 x 62
    public static final Identifier CHARACTER_STAR_DRAGON = id("character/star_dragon"); // 68 x 59

    /**
     * The mod's tooltip look. Not a sprite itself: the game derives the two it draws a tooltip with from
     * it, {@code tooltip/wood_background} and {@code tooltip/wood_frame}.
     */
    public static final Identifier TOOLTIP_STYLE = id("wood");

    // --- the game's own HUD, for the previews to stand in front of ---
    public static final Identifier VANILLA_HOTBAR = Identifier.withDefaultNamespace("hud/hotbar");                    // 182 x 22
    public static final Identifier VANILLA_EXPERIENCE = Identifier.withDefaultNamespace("hud/experience_bar_background"); // 182 x 5
    public static final Identifier VANILLA_HEART = Identifier.withDefaultNamespace("hud/heart/full");                 // 9 x 9
    public static final Identifier VANILLA_HEART_CONTAINER = Identifier.withDefaultNamespace("hud/heart/container");
    public static final Identifier VANILLA_FOOD = Identifier.withDefaultNamespace("hud/food_full");
    public static final Identifier VANILLA_FOOD_EMPTY = Identifier.withDefaultNamespace("hud/food_empty");
    public static final Identifier VANILLA_CROSSHAIR = Identifier.withDefaultNamespace("hud/crosshair");              // 15 x 15

    private Sprites() {
    }

    private static Identifier id(final String path) {
        return Identifier.fromNamespaceAndPath(NAMESPACE, path);
    }

    public static void draw(final GuiGraphicsExtractor graphics, final Identifier sprite, final int x, final int y, final int width, final int height) {
        graphics.blitSprite(RenderPipelines.GUI_TEXTURED, sprite, x, y, width, height);
    }

    /** Draws a sprite multiplied by an ARGB colour: tints the white ones, fades any of them. */
    public static void draw(final GuiGraphicsExtractor graphics, final Identifier sprite, final int x, final int y, final int width, final int height, final int argb) {
        if ((argb >>> 24) != 0) {
            graphics.blitSprite(RenderPipelines.GUI_TEXTURED, sprite, x, y, width, height, argb);
        }
    }

    /**
     * Draws a sprite centred on a point, scaled and rotated - for everything that moves: the pop of a
     * slot, a glow that breathes, the pointer of the wheel.
     */
    public static void drawCentred(final GuiGraphicsExtractor graphics, final Identifier sprite, final float centreX, final float centreY,
                                   final int width, final int height, final float scale, final float radians, final int argb) {
        if ((argb >>> 24) == 0 || scale <= 0.0F) {
            return;
        }
        graphics.pose().pushMatrix();
        graphics.pose().translate(centreX, centreY);
        if (radians != 0.0F) {
            graphics.pose().rotate(radians);
        }
        graphics.pose().scale(scale, scale);
        graphics.blitSprite(RenderPipelines.GUI_TEXTURED, sprite, -width / 2, -height / 2, width, height, argb);
        graphics.pose().popMatrix();
    }
}
